apiVersion: batch/v1 
kind: Job
metadata:
  labels:
    run: cphtestp-1-1
  name: cphtestp-1-1
  namespace: cph-test
spec:
  template:
    metadata:
      labels:
        run: cphtestp-1-1
    spec:
      containers:
      - env:
        - name: LICENSE
          value: accept
        - name: MQ_TLS_SNI_HOSTNAME
          value: "TRUE"
        - name: MQ_TLS_CIPHER
          value: TLS_RSA_WITH_AES_256_GCM_SHA384
        - name: MQ_AUTORECONNECT
          value: MQCNO_RECONNECT
        - name: MQ_RESPONDER_THREADS
          value: "20"
        - name: MQ_NON_PERSISTENT
          value: "0"
        - name: MQ_CCDT
          value: ccdt-ibmdemo01-1
        - name: MQ_QMGR_NAME
          value: IBMDEMO01
        image: docker.io/ldesrosi/cphtestp
        imagePullPolicy: Always
        name: cphtestp
        resources: 
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - name: cphdata
            mountPath: /var/cph
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cphdata
        emptyDir: {}
        
